### ISSUE TITLE
Does not work with Apple File System APFS

### ISSUE THREAD

**Issue by swtdev** [gjoseph/BarbaryWatchService#10]
We need to use a native WatchService implementation due to the Oracle polling one being rubbish, however we have a test suite for our code and it's failing when switching to BarbaryWatchService.

I've discovered this must be due to the Apple File System APFS as the High Sierra machine I'm running the tests on uses this. I also have an external SSD using regular HFS+ and when I configure the tests to run on this (instead of "java.io.tmpdir") then they work just fine.

On APFS the order of events seems to be random, and we're receiving unexpected (stale?) events also.

**Comment by clankill3r** [comment]
Is this still an issue?

**Comment by swtdev** [comment]
We haven't tried since raising this issue, but given the code hasn't changed since then the only way it would be resolved would be if Apple changed something. But if they have can you guarantee all your users would have that change?!

We ended up using a different library, jpathwatch, forking and fixing an issue it contains. It's working well for us. You can try it if Barbary doesn't work out for you..

- https://bitbucket.org/digital-software-technology/jpathwatch-dst

**Comment by clankill3r** [comment]
Thanks for the fast reply.
I will look into it.
I'm planning on making my own simple to use one file library for this, if
that is possible...

Op wo 6 mrt. 2019 om 00:06 schreef swtdev <notifications@github.com>:

**Comment by gjoseph** [comment]
Hi @swtdev @clankill3r sorry for the slow response -- as you may have gathered, I haven't had capacity to maintain this project in a _long_ time. I'm finally officially retiring it. See README for possible alternatives, if you're still needing this. ✌️

**Comment by clankill3r** [comment]
Thanks for the reply. I just gave up on being a perfectionist when using java, so it's ok.
