### ISSUE TITLE
libCarbon.dylib fails to load on MacOS Big Sur

### ISSUE THREAD

**Issue by chancerussell** [gjoseph/BarbaryWatchService#13]
When calling WatchableFile.register on a system running the first beta of MacOS Big Sur, the following exception is thrown:

```
java.lang.UnsatisfiedLinkError: Unable to load library 'Carbon': dlopen(libCarbon.dylib, 9): image not found
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.barbarysoftware.jna.CarbonAPI
```

[This looks to affect other libraries using Carbon for file watching as well](https://github.com/gmethvin/directory-watcher/issues/52)

Per that thread, it [looks like the JNA folks are aware of the issue](https://github.com/java-native-access/jna/pull/1216) .

**Comment by dbwiddis** [comment]
FYI, JNA 5.6.0 has been released.

**Comment by gjoseph** [comment]
Hi @dbwiddis @chancerussell sorry for the slow response -- as you may have gathered, I haven't had capacity to maintain this project in a _long_ time. I'm finally officially retiring it. See README for possible alternatives, if you're still needing this. ✌️
