### ISSUE TITLE
Really slow on macOS Monterey

### ISSUE THREAD

**Issue by bludginozzie** [gjoseph/BarbaryWatchService#15]
This project has lasted 7 years without a code change but it appears that this has now come to an end.  I am finding that this watch service is really slow on Monterey.  In fact it's less performant than the polling watch service provided with the jdk.  Is anyone else seeing this?

**Comment by bludginozzie** [comment]
Further to this, I discovered this project - https://github.com/gmethvin/directory-watcher.

It is more actively maintained and works well on Monterey.

**Comment by gjoseph** [comment]
@bludginozzie @anderseknert apologies for the slow response - as you may have gathered, I've not had any time/energy to devote to this project in a _long_ time. Happy to accept PRs if you want anything done, or transfer ownership. If there are good alternatives out there, happy to link them in the README.

**Comment by anderseknert** [comment]
No worries @gjoseph, this works well enough for my purposes. Thanks! 👍
