### ISSUE TITLE
Figure out possible license issues

### ISSUE THREAD

**Issue by gjoseph** [gjoseph/BarbaryWatchService#2]
The repository contains a bunch of classes that were copied pretty much verbatim from OpenJDK. Is that OK ?

Additionally, I'd like the project to be licensed under a more permissive license than the LGPL. Perhaps this can be changed for the 2.0 release.

**Comment by robertroeser** [comment]
Hi,

I'm interesting in using the library for a project. Did you figure out what license you are going to use?

Thanks,
Robert

**Comment by gjoseph** [comment]
Hi @robertroeser sorry for the slow response -- as you may have gathered, I haven't had capacity to maintain this project in a long time. I'm finally officially retiring it. See README for possible alternatives, if you're still needing this. ✌️
