### ISSUE TITLE
MacOSX WatchService check for null file in recursiveListFiles

### ISSUE THREAD

**Issue by Zillode** [gjoseph/BarbaryWatchService#7]
I did not run into this problem (yet?) but when looking for the most up-to-date source code, I found a [downstream](https://github.com/ReactiveX/RxJavaFileUtils/pull/8) patch to fix a potential NPE: https://github.com/ReactiveX/RxJavaFileUtils/commit/87a68e4e69cc0a96adaf169fc1a9f9a02f1a6054

Maybe you can cherry-pick this?
Thanks for the library, it works pretty well:)

**Comment by gjoseph** [comment]
Hi @Zillode sorry for the slow response -- as you may have gathered, I haven't had capacity to maintain this project in a _long_ time. I'm finally officially retiring it. See README for possible alternatives, if you're still needing this. ✌️

**Comment by Zillode** [comment]
No problem! Thank you for your work and sharing the code 👍 ❤️
