### ISSUE TITLE
Handle symlinks on MAC

### ISSUE THREAD

**Issue by maczikasz** [gjoseph/BarbaryWatchService#9]
Create a folder and a file in a directory that's symlinked (/var/tmp) 
Then start barbary watchservice
Delete the file and the folder
You will receive a Create event to the root folder

The following code, canot handle symlinks:

`                if (file.getAbsolutePath().startsWith(folderName) && !filesOnDisk.contains(file)) {
`
Hence it will not find the files in the lastModifiedMap

**Comment by gjoseph** [comment]
Hi @maczikasz sorry for the slow response -- as you may have gathered, I haven't had capacity to maintain this project in a _long_ time. I'm finally officially retiring it. See README for possible alternatives, if you're still needing this. ✌️

**Comment by maczikasz** [comment]
I did not expect to receive any kind of answer after 5 years :D but I since also moved on from the project that needed it, all the best to you
